# Generated by Django 2.1.2 on 2018-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')], default=0),
        ),
    ]
