# Generated by Django 2.1.2 on 2018-11-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normaluser', '0002_normaluser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
