# Generated by Django 2.1.2 on 2018-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normaluser', '0003_auto_20181104_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='email_validation_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
